### PR TITLE
adding executemany

### PR DESCRIPTION
**Pull request by feinsteinben**
executemany is required for the pandas-vertica integration.

### CODE REVIEW

**Comment by feinsteinben** [comment]
I get an error when using executemany() to upload some tables, saying that the message type 'F' is not recognized.

**Comment by AndrewJudson** [comment]
@feinsteinben Are you still having your issue? Interested in this PR, having pandas functionality would be nice.

**Comment by feinsteinben** [comment]
@AndrewJudson yes. If you're familiar with vertica-python copy(), I'd appreciate your assistance.

**Comment by AndrewJudson** [comment]
I'm pretty unfamiliar with this code but I can try. Is executemany() always failing or only sometimes? If it is only sometimes do you have a minimal example? I found this when searching for message type F in vertica, seems it is some undocumented part of the protocol https://github.com/wvanbergen/node-vertica/issues/28

**Comment by feinsteinben** [comment]
**This pull request is broken. It'll take a while to fix it. Ignore it for now...**

**Comment by feinsteinben** [comment]
See #151

**Pull request closed without merging**
