### PR TITLE
Add flag to specify unicode error options

### PR DESCRIPTION
**Pull request by esmioley**

### CODE REVIEW

**Comment by gabrielhaim** [comment]
Should you bump the version? or are you doing this in another PR?

**Comment by Bennyelg** [comment]
When you creating a method the pep-8 advice:
Identifier Type Format Example
Class Camel | case class StringManipulator():
------------ | -------------
Variable Words joined by _  | joined_by_underscore = True
------------ | -------------
Function Words joined by _ | def multi_word_name(words):
------------ | -------------
**Constant All uppercase SECRET_KEY = 42**

**Comment by esmioley** [comment]
I wasn't sure if it was me or you that would bump the version. I'm happy to do so.

**Comment by esmioley** [comment]
@gabrielhaim version updated
@Bennyelg updated case now that the constants are functions

**Pull request merged**
