### PR TITLE
Adding ConnectionFailure Exception

### PR DESCRIPTION
**Pull request by bradleyhurley**

### CODE REVIEW

**Comment by bradleyhurley** [comment]
I have signed the CLA.  Does the CLAassistant only run when a new commit is pushed, or is something wrong?

**Comment by Subzidion** [comment]
The CLA wasn't working with the rides-python-sdk repo as well (https://github.com/uber/rides-python-sdk/pull/36) Not sure if it's a config issue or if it's a CLA issue.

**Comment by arogal** [comment]
@bradleyhurley I believe this is because your commit is not linked to your github user. Please follow the troubleshooting guide here: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by bradleyhurley** [comment]
Thanks, I linked the email address so hopefully everything is all set with the CLA.

**Comment by arogal** [comment]
@bradleyhurley sorry for the trouble here. Do you think you can create a new pull request quickly please? A manual recheck isn't working and a new PR would probably be fastest. Sorry for the trouble.

**Comment by bradleyhurley** [comment]
Yeah, I will create a new pull request and close this request.

**Pull request closed without merging**
