### PR TITLE
Adding executemany and more

### PR DESCRIPTION
**Pull request by feinsteinben**
Refactored the old PRs into one, to make things easier. Sorry for the rain of not-so-good PRs I made earlier.

### Bug Fixes
1. In _column.py_, `data_type` was a property of `Column`, therefore couldn't be accessed as Column.data_type as it was used in _backend_messages/parameter_description.py_ message. It was changed to a `classmethod` to fix this issue.
2. Several strings compatibility bugs (or things that looked like possible-bugs) were fixed.

### Improvements
1. Added (copied) a compatibility module from Tensorflow. The license is attached to the head of the module.
2. Made messages more object-oriented. It gives several benefits:
  - Standard interface: Use `messge.fetch_message()` (returns a `generator`) for any backend message. If it's a BulkBackendMessage (can be read at once), you can also use `message.get_message()`.
  - Easier and more elegant: backend_messages are now registerd more simply (just `BackendMessage.register(MyBackendMessage)`). The `message_id` is now a property of the class.
  - Resuable code: frontend messages just need to return bytes, and they are trnanslated into a message / messages in FrontendMessage (therefore, this part is only written once).
3. Added executemany to Cursor. This (together with `sqlalchemy-vertica`) should add a full (almost) integration with pandas, which is quite useful.
4. Hopefully, the `copy` method was also improved. Now it uses CopyStream everywhere.

### CODE REVIEW

**Comment by alexjikim** [comment]
will try to get around to reviewing this week

**Comment by alexjikim** [comment]
sweet. thanks for the all the work on this.

**Comment by karthiksharmasg** [comment]
Hi,
First of all, Thanks for the great work on providing a stable python interface for vertica,
This is regarding the executemany and panda intergration, below is my test code

import pandas as pd
import sqlalchemy as sa

engine = sa.create_engine("vertica+vertica_python://user:password@host:port/database")
connection = engine.connect()
data = pd.read_sql('select * from pythondemo',connection)
data.to_sql(name='pythondemo,con = engine,if_exists = 'append',index=False)


this will end up in following error.
NotImplementedError: executemany is implemented for simple INSERT statements only

I know this is because the regex is not correct, but am I doing something wrong or we have to correct the regex?

the regex created by pandas in the scenario is 
INSERT INTO "pythonDemon1" (x, y) VALUES (:x, :y)

Thanks

**Comment by feinsteinben** [comment]
Hi @karthiksharmasg,

I pushed something that may fix the problem you've raised.
Please tell me if it works for you.

Bests regrads,
Ben

**Comment by karthiksharmasg** [comment]
hi ben,

the code changes doesnt match the string,

i have modified your code as below

RE_NAME_BASE = u"[a-zA-Z_][\\w\\d\\$_]*"
RE_NAME = u'("{0}")|({0})'.format(RE_NAME_BASE)
RE_BASIC_INSERT_STAT = (
    u"INSERT\\s+INTO"
    "\\s+((?P<schema>{0})\\.)?(?P<table>{0})"
    "\\s*\\(\\s*(?P<variables>(({0})(\\s*,\\s*({0}))*)?\\s*)\\)"
    "\\s+VALUES\\s*\\(\\s*(?P<values>.*)\\)").format(RE_NAME)


this works for me.
and since schema is not part of the query as_text will fail,

**Pull request merged**
